volumes:
  lvm:
  save:
  data:

services:

  builder:
    image: glusterbuild
    build:
      context: .
      target: builder
    working_dir: /src
    volumes:
    - ./src/:/src

  glusterfs:
    image: gluster/gluster-centos
    hostname: glusterfs
    privileged: true
    network_mode: host
    environment:
      CGROUP_PIDS_MAX: 0
    volumes:
      - lvm:/run/lvm
      - save:/var/lib/glusterd
      - data:/data
    