version: "3.7"

services:

  builder:
    image: glusterbuild
    build:
      context: builder
    working_dir: /src
    volumes:
      - ./:/src
      - ./test:/usr/local/go/src/test

#  test-volume:
#    driver: docker-volume-glusterfs:latest
